### ISSUE TITLE
SSL/TLS handshake error

### ISSUE THREAD

**Issue by simokassab** [shuchkin/react-smtp-client#2]
Dear,

below is my code:

```
require_once './vendor/autoload.php';
$loop = \React\EventLoop\Factory::create();

$smtp = new \Shuchkin\ReactSMTP\Client( $loop, 'tls://smtp.gmail.com:465', 'mohammad.a.kassab@gmail.com','MYPASSWORD' );

$smtp->send('mohammad.a.kassab@gmail.com', 'mohammad.a.kassab@gmail.com', 'Test ReactPHP mailer', 'Hello, Sergey!')->then(
	function() {
		echo 'Message sent via Google SMTP'.PHP_EOL;
	},
	function ( \Exception $ex ) {
		echo 'SMTP error '.$ex->getCode().' '.$ex->getMessage().PHP_EOL;
	}
);
$loop->run();
```

i got this error: SMTP error 2 Unable to complete SSL/TLS handshake: failed loading cafile stream: `C:\xampp\apache\bin\curl-ca-bundle.crt'

open_ssl is enabled on my apache.

thanks

**Comment by shuchkin** [comment]
https://odan.github.io/2017/03/30/xampp-curl-ssl-setup.html

1. Download: http://curl.haxx.se/ca/cacert.pem
2. Copy the file cacert.pem into the directory: C:\xampp\php\extras\ssl\
3. Open c:\xampp\php\php.ini with Notepad++
4. Search for the [curl] section
5. Add the following lines:

[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo="C:\xampp\php\extras\ssl\cacert.pem"
openssl.cafile="C:\xampp\php\extras\ssl\cacert.pem"

**Comment by simokassab** [comment]
Great it worked very well,

but this take about 4-5 seconds to send the email, and this should run the email function in background right ?

**Comment by shuchkin** [comment]
Async, NOT background
See https://reactphp.org/

CLI only, don't use it in your Apache/Nginx environment
